ProZdorovye/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from landing.views import MainView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('services/', include('services.urls', namespace='services')),
    path('prices/', include('prices.urls', namespace='prices')),
    path('blog/', include('articles.urls', namespace='articles')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('', include('landing.urls', namespace='landing')),
    path('', MainView.as_view()),
    re_path(r'^sitemap\.xml$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'sitemap.xml',
    }),
    re_path(r'^robots\.txt$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'robots.txt',
    }),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'landing.views.handler404'

prices/urls.py
from django.urls import path
from .views import *


app_name = 'prices'


urlpatterns = [
    path('', PricesView.as_view(), name='prices'),
    path('search/', ServiceSearchView.as_view(), name='search'),

    path('api/prices/', PricesAPIView.as_view(), name='prices_api'),
]

vacancies/urls.py
from django.urls import path
from .views import *


app_name = 'vacancies'


urlpatterns = [
    path('', VacanciesView.as_view(), name='vacancies'),
    path('<slug:vacancy_slug>/', VacancyView.as_view(), name='vacancy'),
    path('api/save_reply/', SaveVacancyReply.as_view(), name='vacancy'),
]

vacancies/models.py
from django.db import models
from django.urls import reverse


class Vacancy(models.Model): 
    title = models.CharField('Название', max_length=120) 
    preamble = models.TextField('Преамбула') 
    duties = models.TextField('Обязанности') 
    requirements = models.TextField('Требования') 
    conditions = models.TextField('Условия') 
    ending = models.TextField('Окончание') 
    created_at = models.DateTimeField('Дата и время публикации', auto_now_add=True)
    slug = models.SlugField('Слаг', max_length=500)

    class Meta: 
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

    def __str__(self):
        return f'{self.title} ({self.created_at})'
    
    def get_absolute_url(self) -> str: 
        return reverse('vacancies:vacancy', args=[self.slug])



class VacancyReply(models.Model): 
    last_name = models.CharField('Фамилия', max_length=50) 
    first_name = models.CharField('Имя', max_length=50) 
    phone = models.CharField('Телефон', max_length=18) 
    resume = models.FileField('Резюме', upload_to='vacancies/replies/', null=True, blank=True)
    is_closed = models.BooleanField('Обработано', default=False)

    class Meta: 
        verbose_name = 'Отклик на вакансию'
        verbose_name_plural = 'Отклики'

    def __str__(self) -> str: 
        return f'{self.is_closed} | {self.last_name}, {self.phone}'

vacancies/forms.py
from django import forms 
from .models import VacancyReply


class VacancyReplyForm(forms.ModelForm): 
    class Meta:
        model = VacancyReply
        fields = ['last_name', 'first_name', 'phone', 'resume']
        labels = {
            'last_name': 'Фамилия',
            'first_name': 'Имя',
            'phone': 'Телефон',
            'resume': 'Резюме',
        }
        widgets = {
            'last_name': forms.TextInput(attrs={'class': 'form__input'}),
            'first_name': forms.TextInput(attrs={'class': 'form__input'}),
            'phone': forms.TextInput(attrs={'class': 'form__input'}),
            'resume': forms.FileInput(
                attrs={
                    'class': 'form__input', 
                    "class": "input-file",
                    "accept": ".pdf,.doc,.docx",
            })
        }

vacancies/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View 
from landing.tasks import send_email_task
from django.http import JsonResponse
from .models import Vacancy
from .forms import VacancyReplyForm


class VacanciesView(View): 
    template_name = 'vacancies/vacancies.html'

    def get(self, request): 
        vacancies = Vacancy.objects.all()
        context = {
            'vacancies': vacancies,
        }
        return render(request, self.template_name, context)


class VacancyView(View): 
    template_name = 'vacancies/vacancy.html' 

    def get(self, request, vacancy_slug: str): 
        vacancy = get_object_or_404(Vacancy, slug=vacancy_slug)
        form = VacancyReplyForm()
        context = {
            'vacancy': vacancy,
            'form': form,
        }
        return render(request, self.template_name, context)
    

class SaveVacancyReply(View):
    def post(self, request): 
        form = VacancyReplyForm(request.POST, request.FILES) 
        if form.is_valid(): 
            new_reply = form.save() 

            subject = f'Отклик на вакансию от {new_reply.phone}'
            message = (
                f'Номер телефона: {new_reply.phone}' 
                f'\nИмя: {new_reply.first_name}'
                f'\nФамилия: {new_reply.last_name}'
            )

            email_data = {
                "subject": subject,
                "message": message,
            }

            if new_reply.resume:
                email_data["resume_path"] = new_reply.resume.path
            
            send_email_task.delay(**email_data)

            return JsonResponse({'status': 'ok'})
        return JsonResponse({
            'errors': form.errors
        })

vacancies/templates/vacancies/vacancies.html
{% extends 'base.html' %} {% load static %}
{% load article_tags %}

{% block title %} Вакансии - Медицинский центр ПроЗдоровье {% endblock %}
{% block meta_title %} Вакансии - Медицинский центр ПроЗдоровье {% endblock %}
{% block description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи
и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия.
ПроЗдоровье - здоровье начинается здесь! {% endblock %}
{% block meta_description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи,
эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на
индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %}

{% block script %}
<script type=module crossorigin src="{% static 'js/header.js' %}"></script>
<script type=module crossorigin src="{% static 'js/booking.js' %}"></script>
<script type=module crossorigin src="{% static 'js/ask-form.js' %}"></script>
<script type=module crossorigin src="{% static 'js/footer.js' %}"></script>
{% endblock %} {% block content %}
<div class=blog-list-page>
    <div id=header></div>
    <div class="section section--inpage">
        <div class="container blog-list">
            <h1 class=blog-list__header>Вакансии</h1>
            <div class=content>
                <div class="content__main content__main-vacancies">
                    {% for vacancy in vacancies %}
                    <a class="article vacancy" href="{{ vacancy.get_absolute_url }}">
                        <div class=article__title>{{ vacancy.title }}</div>
                        <div class=article__text>
                            <p>
                                {{ vacancy.preamble|remove_markdown_chars }}
                            </p>
                        </div>
                        <div class="article__date article__date-vacancy">{{ vacancy.created_at|date:" d.m.Y" }}</div>
                        <div class="vacancies__to-do-vacancy-block ">
                            <button type="submit" class="form__button button-osta">Подробнее</button>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div id=doctors></div>
    <div id=booking></div>
    <div id=ask-form></div>
    <div id=footer></div>
</div>
{% endblock %}

vacancies/templates/vacancies/vacancy.html
{% extends 'base.html' %} {% load static %}
{% load article_tags %}

{% block title %} {{ vacancy.title }} - Медицинский центр ПроЗдоровье {% endblock %}
{% block meta_title %} {{ vacancy.title }} - Медицинский центр ПроЗдоровье {% endblock %}
{% block description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи
и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия.
ПроЗдоровье - здоровье начинается здесь! {% endblock %}
{% block meta_description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи,
эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на
индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %}

{% block script %}
<script type=module crossorigin src="{% static 'js/header.js' %}"></script>
<script type=module crossorigin src="{% static 'js/booking.js' %}"></script>
<script type=module crossorigin src="{% static 'js/ask-form.js' %}"></script>
<script type=module crossorigin src="{% static 'js/footer.js' %}"></script>
<script src="{% static 'js/vendor/Imask.min.js' %}" defer></script>
{% endblock %} {% block content %}
<div class=blog-list-page>
    <div id=header></div>
    <div class="section section--inpage">
        <div class="container blog-list">
            <h1 class="blog-list__header blog-list__header-vacancy">Вакансия "{{ vacancy.title }}"</h1>
            <div class=content>
                <div class=content__main>
                    <div class=content__intro>
                        {{ vacancy.preamble|markdown }}
                    </div>
                    <div class=content__description>
                        {{ vacancy.duties|markdown }}
                    </div>
                    <div class=content__description>
                        {{ vacancy.requirements|markdown }}
                    </div>
                    <div class=content__description>
                        {{ vacancy.conditions|markdown }}
                    </div>
                </div>
                <div class=directions>
                        <form id="vacancyReplyForm" class=form method=post>
                            {% csrf_token %}
                            <div class="form__title form__title-vacancy">Откликнуться на вакансию</div>
                            <div class=form__field>
                                {{ form.last_name }}
                                <label for="{{ form.last_name.id_for_label }}" class=form__label>{{ form.last_name.label }}</label>
                            </div>
                            <div class=form__field>
                                {{ form.first_name }}
                                <label for="{{ form.first_name.id_for_label }}" class=form__label>{{ form.first_name.label }}</label>
                            </div>
                            <div class=form__field>
                                {{ form.phone }}
                                <label for="{{ form.phone.id_for_label }}" class=form__label>{{ form.phone.label }}</label>
                            </div>
                            <div class=form__field>
                                <label class="input-file">
                                    {{ form.resume }}
                                     <span class="input-file-btn">Прикрепить резюме</span>           
                                    <span class="input-file-text">Максимум 5Мб</span>
                              </label>
                            </div>
                            <button type=submit class="form__button button-osta">
                                Откликнуться
                            </button>
                        </form>
                </div>
            </div>
        </div>
    </div>
    <div id=doctors></div>
    <div id=booking></div>
    <div id=ask-form></div>
    <div id=footer></div>
</div>

<script
  src="https://code.jquery.com/jquery-3.6.3.js"
  integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
  crossorigin="anonymous">
</script>
<script src="{% static 'js/vendor/Imask.min.js' %}" defer></script>
<script>
// Поле для резюме
const form = document.querySelector("#vacancyReplyForm");
const fileInput = document.querySelector('.input-file input[type=file]');
const fileText = document.querySelector('.input-file .input-file-text');

// Обработчик выбора файла
fileInput.addEventListener('change', function(event) {
    let file = event.target.files[0];
    if (file) {
        fileText.textContent = file.name;
    } else {
        fileText.textContent = "Максимум 5Мб"; 
    }
});

document.addEventListener("DOMContentLoaded", function() {
// Маска для телефона
    var phoneInput = document.querySelector("#id_phone"),
    phoneMask = IMask(phoneInput, {
        mask: "+{7} (000) 000 00 00"
    });

    function validatePhoneNumber() {
    let t = phoneInput.value.replace(/\D/g, "");
    return t.length < 11 ? (phoneInput.setCustomValidity("Необходимо минимум 11 цифр"), !1) : (phoneInput.setCustomValidity(""), !0)
    }
    phoneInput.addEventListener("input", function() {
    validatePhoneNumber()
    });
    const toastHtml = `
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="toastRequestSent" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <img src="${window.origin}/static/images/favicon-16x16.png" class="rounded me-2" alt="Иконка">
        <strong class="me-auto">Форма была отправлена!</strong>
        <small>только что</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        Спасибо за отклик на вакансию.
    </div>
    </div>
    </div>
    `;

    function showToast() {
    document.body.insertAdjacentHTML("beforeend", toastHtml);
    let t = document.getElementById("toastRequestSent"),
        a = bootstrap.Toast.getOrCreateInstance(t);
    a.show(), t.addEventListener("hidden.bs.toast", () => {
        t.remove()
    })
    }

    const form = document.querySelector("#vacancyReplyForm");
    form.addEventListener("submit", async function(t) {
        t.preventDefault();
        
        let a = new FormData(form);

        if (fileInput.files.length > 0) {
            a.append("resume", fileInput.files[0]);
        } 

        console.log(a)

        e = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
        form.reset(), showToast();
        fileText.textContent = "Максимум 5Мб";
        try {
            let n = await fetch(`/vacancies/api/save_reply/`, {
                method: "POST",
                body: a,
                headers: {
                    "X-CSRFToken": e
                }
            });
            console.log(n.json())
        } catch (o) {
            console.error("Ошибка запроса:", o)
        }
    });
})
</script>
{% endblock %}