ProZdorovye/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from landing.views import MainView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('services/', include('services.urls', namespace='services')),
    path('prices/', include('prices.urls', namespace='prices')),
    path('blog/', include('articles.urls', namespace='articles')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('', include('landing.urls', namespace='landing')),
    path('', MainView.as_view()),
    re_path(r'^sitemap\.xml$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'sitemap.xml',
    }),
    re_path(r'^robots\.txt$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'robots.txt',
    }),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'landing.views.handler404'

articles/urls.py
from django.urls import path
from .views import *


app_name = 'articles'


urlpatterns = [
    path('articles/', ArticlesListView.as_view(), name='articles_list'),
    path('<slug:article_slug>/', ArticleView.as_view(), name='article'),
]

doctors/urls.py
from django.urls import path
from .views import *


app_name = 'doctors'


urlpatterns = [
    path('doctor/<slug:doctor_slug>/', DoctorView.as_view(), name='doctor'),
    path('', DoctorsView.as_view(), name='doctors'),
    
    path('api/doctors/', DoctorsAPIView.as_view(), name='api_doctors'), 
]

landing/urls.py
from django.urls import path
from .views import *


app_name = 'landing'


urlpatterns = [
    path('', HomeView.as_view(), name='home'), 
    path('map/', MapView.as_view(), name='map'),
    path('contacts/', ContactsView.as_view(), name='contacts'), 
    path('juridical/', JuridicalInfoView.as_view(), name='juridical_info'), 
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('api/get_request_form_html/', RequestFormHtmlApi.as_view(), name='request_form_html'),
    path('api/get_question_form_html/', QuestionFormHtmlApi.as_view(), name='question_form_html'),
    path('api/get_contact_info_html/', ContactInfoHtmlApi.as_view(), name='contact_info_html'),
    path('api/save_request/', SaveRequestView.as_view(), name='save_request'),
    path('api/save_question/', SaveQuestionView.as_view(), name='save_question'),
    path('api/get_phone_number/', PhoneNumberApi.as_view(), name='get_phone_number'),
]

handler404 = 'landing.views.handler404'

prices/urls.py
from django.urls import path
from .views import *


app_name = 'prices'


urlpatterns = [
    path('', PricesView.as_view(), name='prices'),
    path('search/', ServiceSearchView.as_view(), name='search'),

    path('api/prices/', PricesAPIView.as_view(), name='prices_api'),
]

services/urls.py
from django.urls import path
from .views import *


app_name = 'services'


urlpatterns = [
    path('<slug:speciality_slug>', ServicesView.as_view(), name='speciality'),

    path('api/specialities/', SpecialitiesAPIView.as_view(), name='specialities_api'),
    path('api/profession_mapper/', ProfessionsMapperAPIView.as_view(), name='professions_mapper_api'),
]

landing/forms.py
from django import forms 
from .models import Request, Question


class RequestForm(forms.ModelForm): 
    class Meta:
        model = Request
        fields = ['name', 'phone', 'email']
        labels = {
            'name': 'Имя',
            'phone': 'Телефон',
            'email': 'Электронная почта',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form__input'}),
            'phone': forms.TextInput(attrs={'class': 'form__input', 'minlength': 18}),
            'email': forms.EmailInput(attrs={'class': 'form__input'}),
        }


class QuestionForm(forms.ModelForm): 
    class Meta:
        model = Question
        fields = ['name', 'phone', 'email', 'text']
        labels = {
            'name': 'Имя',
            'phone': 'Телефон',
            'email': 'Электронная почта',
            'text': 'Сообщение',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form__input'}),
            'phone': forms.TextInput(attrs={'class': 'form__input', 'minlength': 18}),
            'email': forms.EmailInput(attrs={'class': 'form__input'}),
            'text': forms.Textarea(attrs={'class': 'form__input', 'rows': 4}),
        }

landing/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.template import RequestContext
from doctors.models import Speciality, Doctor
from reviews.models import Review
from articles.models import Article
from .forms import RequestForm, QuestionForm
from .tasks import send_email_task
from .models import (
    UserAgreementPDF, 
    ContactInfo, 
    LicensePage, 
    JuridicalInfo,
    ProcessingDataAgreement, 
    FilialInfo, 
)


class MainView(View): 
    def get(self, request): 
        return redirect('landing:home')


class HomeView(View): 
    template_name = 'landing/home.html' 

    def get(self, request): 
        speclialities = Speciality.objects.all()
        reviews = Review.objects.all()
        doctors = Doctor.objects.all()
        articles = Article.objects.all()
        form = RequestForm()

        context = {
            'specialities': speclialities,
            'reviews': reviews,
            'doctors': doctors,
            'articles': articles,
            'form': form,
        }

        return render(request, self.template_name, context)
    

class SaveRequestView(View): 
    def post(self, request): 
        form: RequestForm = RequestForm(request.POST) 
        if form.is_valid(): 
            new_request = form.save() 
            
            subject = f'Контактные данные от {new_request.phone}'
            message = (
                f'Номер телефона: {new_request.phone}'
                f'\nИмя: {new_request.name}'
            )
            if new_request.email:
                message += f'\nE-mail: {new_request.email}'
            
            send_email_task.delay(subject=subject, message=message)

            return JsonResponse({'status': 'ok'})
        return JsonResponse({'status': 'error'})
    

class SaveQuestionView(View): 
    def post(self, request): 
        form = QuestionForm(request.POST) 
        if form.is_valid(): 
            new_question = form.save() 

            subject = f'Вопрос от {new_question.phone}'
            message = (
                f'Номер телефона: {new_question.phone}' 
                f'\nИмя: {new_question.name}'
            )
            if new_question.email:
                message += f'\nE-mail: {new_question.email}'
            if new_question.text: 
                message += f'\nСодержание: {new_question.text}'
            
            send_email_task.delay(subject=subject, message=message)

            return JsonResponse({'status': 'ok'})
        return JsonResponse({'status': 'error'})
    

class ContactsView(View): 
    template_name = 'landing/contacts.html' 

    def get(self, request): 
        return render(request, self.template_name)
    

class RequestFormHtmlApi(View): 
    def get(self, request): 
        form = RequestForm()
        user_agreement_url = UserAgreementPDF.get_instance().file.url
        processing_data_agreement_url = ProcessingDataAgreement.get_instance().file.url
        contact_info = ContactInfo.get_instance()
        context = {
            'form': form, 
            'processing_data_agreement_url': processing_data_agreement_url,
            'user_agreement_url': user_agreement_url,
            'contact_info': contact_info,
        }
        form_html = render(request, 'landing/forms/request_form.html', context).content.decode('utf-8')
        return JsonResponse(form_html, safe=False)
    

class QuestionFormHtmlApi(View): 
    def get(self, request): 
        form = QuestionForm()
        user_agreement_url = UserAgreementPDF.get_instance().file.url
        processing_data_agreement_url = ProcessingDataAgreement.get_instance().file.url
        context = {
            'form': form, 
            'processing_data_agreement_url': processing_data_agreement_url,
            'user_agreement_url': user_agreement_url,
        }
        form_html = render(request, 'landing/forms/question_form.html', context).content.decode('utf-8')
        return JsonResponse(form_html, safe=False)
        

class ContactInfoHtmlApi(View): 
    def get(self, request): 
        contact_info = ContactInfo.get_instance()
        license_pages = LicensePage.objects.all()
        context = {
            'contact_info': contact_info, 
            'license_pages': license_pages,
        }
        form_html = render(request, 'landing/forms/contact_info.html', context).content.decode('utf-8')
        return JsonResponse(form_html, safe=False)
    

class PhoneNumberApi(View): 
    def get(self, request): 
        phone_number = ContactInfo.get_instance().filials.all().first().phone 
        data = {
            'phone': phone_number,
        }
        return JsonResponse(phone_number, safe=False)
    

class MapView(View): 
    def get(self, request): 
        specialities = Speciality.objects.all()
        doctors = Doctor.objects.all()
        context = {
            'specialities': specialities,
            'doctors': doctors,
        }
        return render(request, 'landing/map.html', context)
    

class JuridicalInfoView(View): 
    def get(self, request): 
        juridical_info = JuridicalInfo.get_instance()
        context = {
            'juridical_info': juridical_info
        }
        return render(request, 'landing/juridical_info.html', context)
    

class PrivacyPolicyView(View): 
    def get(self, request): 
        user_agreement_url = UserAgreementPDF.get_instance().file.url
        return redirect(user_agreement_url)
    

class PageNotFoundView(View): 
    def get(self, request): 
        specialities = Speciality.objects.all()
        context = {
            'specialities': specialities,
        }
        return render(request, 'landing/page_not_found.html', context)
    
    
def handler404(request, *args, **argv):
    specialities = Speciality.objects.all()
    context = {
        'specialities': specialities,
    }
    return render(request, 'landing/page_not_found.html', context, status=404)

landing/templates/landing/contacts.html
{% extends 'base.html' %} {% load static %} {% block title %} Медицинский центр ПроЗдовье - контакты, адреса на карте, номер телефона {% endblock %} {% block meta_title %} Медицинский центр ПроЗдовье - контакты, адреса на карте, номер телефона {% endblock %} {% block description %} Медицинский центр ПроЗдорвье расположен прямо в центре города.🏥 Вы можете связаться с нами любым удобным способом или записаться онлайн на нашем сайте {% endblock %} {% block meta_description %} Медицинский центр ПроЗдорвье расположен прямо в центре города.🏥 Вы можете связаться с нами любым удобным способом или записаться онлайн на нашем сайте {% endblock %} {% block script %}
<script type=module src="{% static 'js/header.js' %}"></script>
<script type=module src="{% static 'js/booking.js' %}"></script>
<script type=module src="{% static 'js/contactPage.js' %}"></script>
<script type=module src="{% static 'js/ask-form.js' %}"></script>
<script type=module src="{% static 'js/footer.js' %}"></script>
<script type=module src="{% static 'js/luminous-lightbox.js' %}"></script>

{% endblock script %} {% block content %}
<div id=header></div>
<div id=contact></div>
<div id=ask-form></div>
<div id=booking></div>
<div id=footer></div>
{% endblock %}

landing/templates/landing/home.html
{% extends 'base.html' %} {% load static %}
{% block title %} Медицинский центр &quot;ПроЗдоровье&quot; - профессиональный индивидуальный комплексный подход к вашему Здоровью {% endblock %}
{% block meta_title %} Медицинский центр &quot;ПроЗдоровье&quot; - профессиональный индивидуальный комплексный подход к вашему Здоровью {% endblock %}
{% block description %} Медицинский центр &quot;ПроЗдоровье&quot; - профессиональный индивидуальный комплексный подход к вашему Здоровью {% endblock %}
{% block meta_description %} Медицинский центр &quot;ПроЗдоровье&quot; - профессиональный индивидуальный комплексный подход к вашему Здоровью {% endblock %}
{% block script %}
<script type=module src="{% static 'js/header.js' %}"></script>
<script type=module src="{% static 'js/doctors.js' %}"></script>
<script type=module src="{% static 'js/booking.js' %}"></script>
<script type=module src="{% static 'js/contact.js' %}"></script>
<script type=module src="{% static 'js/footer.js' %}"></script>
<script type=module src="{% static 'js/homepage.js' %}"></script>
{% endblock %} {% block content %}
<!doctype html>
<html lang=en>
<div id=header></div>
<div class="section section--hero">
    <div class="promo container">
        <div class=promo__info>
            <h1 class=promo__title>
                Путь
                <br>
                к здоровью <br>начинается
                <br>
                <span class="promo__title promo__title--highlight">здесь</span>
            </h1>
            <div class=promo__description>
                Опытные врачи и современные методы лечения
                <br>
                для поддержания вашего здоровья и благополучия
            </div>
        </div>
        <div class=promo__actions>
            <a href="https://booking.medflex.ru/?user=5c4da05a2aec068f47734a86101c9333" class=button-osta
                target=_blank>Записаться на прием</a>
            <a href=#sectionContact class="button-osta button-osta--secondary">Задать вопрос</a>
        </div>
    </div>
    <div class="service-slider container embla" id=service-list-slider>
        <div class=embla__container>
            {% for speciality in specialities %}
                {% if speciality.is_displayed_on_homepage %}
                    <a href="
                    {% if speciality.is_displayed %}
                        {{ speciality.get_absolute_url }}
                    {% else %}
                        {{ specialities.0.get_absolute_url }}
                    {% endif %}" class="service-slider__item embla__slide">
                        <div class=service-slider__item-info>
                            <div class=service-slider__item-title>
                                {{ speciality.display_name|linebreaks }}
                            </div>
                            <div class=service-slider__item-subtitle>
                                {{ speciality.intro }}
                            </div>
                        </div>
                        <img class=service-slider__item-icon src="{{ speciality.icon.url }}" alt="Иконка">
                    </a>
                {% endif %} 
            {% endfor %}
        </div>
        <button class="embla__button embla__button--prev" type=button>
            <img src="{% static 'images/left.svg' %}" alt="Влево">
        </button>
        <button class="embla__button embla__button--next" type=button>
            <img src="{% static 'images/right.svg' %}" alt="Вправо">
        </button>
    </div>
</div>
<div class="section section--stat">
    <div class="stats-list container">
        <div class=stats-item>
            <div class=stats-item__number>14 000+</div>
            <div class=stats-item__divider></div>
            <div class=stats-item__description>
                Пациентов, прошедших успешное лечение в нашей клинике
            </div>
        </div>
        <div class=stats-item>
            <div class=stats-item__number>15+</div>
            <div class=stats-item__divider></div>
            <div class=stats-item__description>
                Лет опыта работы<br>
                наших специалистов
            </div>
        </div>
        <div class=stats-item>
            <div class=stats-item__number>40+</div>
            <div class=stats-item__divider></div>
            <div class=stats-item__description>
                Специалистов<br>
                в штате клиники
            </div>
        </div>
        <div class=stats-item>
            <div class=stats-item__number>94%</div>
            <div class=stats-item__divider></div>
            <div class=stats-item__description>
                Пациентов приходят по рекомендациям
            </div>
        </div>
        <div class=stats-item>
            <div class=stats-item__number>2</div>
            <div class=stats-item__divider></div>
            <div class=stats-item__description>
                Филиала с удобным<br>
                местоположением
            </div>
        </div>
    </div>
</div>
<div class="section section--clinic-info">
    <div class="clinic-info container">
        <div class=clinic-description>
            <div class=clinic-description__title>О Клинике</div>
            <div class=clinic-description__text>
                Мы – многопрофильная медицинская клиника, предоставляющая широкий спектр услуг для поддержания здоровья
                и благополучия. Наша команда специалистов использует современные методы диагностики и лечения,
                обеспечивая индивидуальный подход и высокое качество медицинской помощи.
            </div>
            <div class="clinic-image__thumbs embla" id=thumbCarousel>
                <div class=embla__container>
                    <div class=embla__slide>
                        <img class="clinic-image__thumbs-image clinic-image__thumbs-image--active"
                            src="{% static 'images/clinic/1.webp' %}" alt="Фото клиники">
                    </div>
                    <div class=embla__slide>
                        <img class=clinic-image__thumbs-image src="{% static 'images/clinic/2.webp' %}"
                            alt="Фото клиники">
                    </div>
                    <div class=embla__slide>
                        <img class=clinic-image__thumbs-image src="{% static 'images/clinic/3.webp' %}"
                            alt="Фото клиники">
                    </div>
                </div>
            </div>
        </div>
        <div class="clinic-image embla" id=mainCarousel>
            <div class=embla__container>
                <div class=embla__slide>
                    <img class=clinic-image src="{% static 'images/clinic/1.webp' %}" alt="Фото клиники">
                </div>
                <div class=embla__slide>
                    <img class=clinic-image src="{% static 'images/clinic/2.webp' %}" alt="Фото клиники">
                </div>
                <div class=embla__slide>
                    <img class=clinic-image src="{% static 'images/clinic/3.webp' %}" alt="Фото клиники">
                </div>
            </div>
        </div>
    </div>
    <div class="clinic-benefits container">
        <div class=benefit>
            <img class=benefit__icon src="{% static 'images/diamont.svg' %}" alt="Иконка">
            <div class=benefit__title>Индивидуальный подход</div>
        </div>
        <div class=benefit>
            <img class=benefit__icon src="{% static 'images/sert.svg' %}" alt="Иконка">
            <div class=benefit__title>Высокая квалификация специалистов</div>
        </div>
        <div class=benefit>
            <img class=benefit__icon src="{% static 'images/lamp.svg' %}" alt="Иконка">
            <div class=benefit__title>Использование современных технологий</div>
        </div>
    </div>
    <div class="clinic-services container">
        <div class=clinic-services__title>Услуги клиники</div>
        <div class=clinic-services__list>
            {% for speciality in specialities %}
            {% if speciality.is_displayed %}
                <a href="{{ speciality.get_absolute_url }}" class=service-button>{{ speciality.name }}</a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<div id=booking></div>
<div id=doctors></div>
<div class="section section--reviews">
    <div class="reviews-section container">
        <div class=reviews-header>Отзывы</div>
        <div class=reviews-list>
            {% for review in reviews|slice:"4" %}
            <div class=review-card>
                <div class=review-card__rating>
                    <img class=review-card__rating-image src="{% static 'images/star.svg' %}" alt="Иконка">
                    <div class=review-card__rating-score>{{ review.rate }}</div>
                    <div class=review-card__rating-status>Отлично</div>
                </div>
                <div class=review-card__text>
                    {{ review.content }}
                </div>
                <div class=review-card__date>Приём был {{ review.created_at|date:"d.m.Y" }}</div>
            </div>
            {% endfor %}
        </div>
        <div class=reviews-footer>
            <div class=reviews-footer__all-reviews>Все отзывы</div>
            <div class=reviews-footer__see-all-list>
                <a href=https://2gis.ru/vladivostok/firm/70000001021276207 target=_blank
                    class=reviews-footer__see-all-item>
                    <img src="{% static 'images/2gis.svg' %}" alt="2GIS">
                </a>
                <a href="https://yandex.ru/maps/org/prozdorovye/54915419883/?ll=131.950981%2C43.172179&z=17"
                    target=_blank class=reviews-footer__see-all-item>
                    <img src="{% static 'images/ya.svg' %}" alt="Яндекс">
                </a>
            </div>
        </div>
    </div>
</div>
<div class="section section--blog">
    <div class="blog container">
        <div class=blog__header>О вашем здоровье</div>
        <div class=blog__content>
            {% for article in articles|slice:"3" %}
            <a class=article href="{{ article.get_absolute_url }}">
                {% if article.image %}
                <img class=article__image src="{{ article.image.url }}" alt="Фото статьи">
                {% endif %}
                <div class=article__title>{{ article.title }}</div>
                <div class=article__text>
                    <p>
                        {{ article.content }}
                    </p>
                </div>
                <div class=article__date>{{ article.created_at|date:"d.m.Y" }}</div>
            </a>
            {% endfor %}
        </div>
        <div class=blog__footer>
            <a href="{% url 'articles:articles_list' %}" class="blog__see-all button-osta">Все статьи</a>
        </div>
    </div>
</div>
<div id=contact></div>
<div id=footer></div>
<script
    type=module>import{printDoctors}from"{% static 'js/doctors.js' %}";document.addEventListener("DOMContentLoaded",(function(){printDoctors("Наши специалисты","Все направления")}))</script>
{% endblock %}

</html>

landing/templates/landing/juridical_info.html
{% extends 'base.html' %} 
{% load static %} 
{% load article_tags %} 
{% block title %} Юридическая информация - Медицинский центр ПроЗдоровье {% endblock %} 
{% block meta_title %} Юридическая информация - Медицинский центр ПроЗдоровье {% endblock %} 
{% block description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %} 
{% block meta_description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %} 

{% block script %}
<script type=module src="{% static 'js/header.js' %}"></script>
<script type=module src="{% static 'js/booking.js' %}"></script>
<script type=module src="{% static 'js/ask-form.js' %}"></script>
<script type=module src="{% static 'js/footer.js' %}"></script>
{% endblock %} {% block content %}
<div class=service-page>
    <div id=header></div>
    <div class="section section--inpage">
        <div class="container service juridical">
            <h1 class=service__header>Юридическая информация</h1>
            <div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Полное наименование медицинской организации</p>
                    <p class="juridical__info">
                        {{ juridical_info.orgainzation_full_name }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Адрес юридического лица </p>
                    <p class="juridical__info">
                        {{ juridical_info.address }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">ОГРН</p>
                    <p class="juridical__info">
                        {{ juridical_info.ogrn }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Наименование зарегистрировавшего органа</p>
                    <p class="juridical__info">
                        {{ juridical_info.registered_authority_name }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Дата государственной регистрации</p>
                    <p class="juridical__info">
                        {{ juridical_info.registering_date }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">ИНН</p>
                    <p class="juridical__info">
                        {{ juridical_info.inn }}
                    </p>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Сведения об учредителях</p>
                    <div class="juridical__info">
                        <p>
                            {{ juridical_info.founders_info|linebreaks }}
                        </p>
                    </div>
                </div>
                <div class="juridical__paragraph">
                    <p class="juridical__label">Сведения о лицензии на осуществление медицинской деятельности</p>
                    <div class="juridical__info">
                        <p>
                            {{ juridical_info.license_info|linebreaks }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id=booking></div>
    <div id=ask-form></div>
    <div id=footer></div>
</div>
{% endblock %}

landing/templates/landing/map.html
{% extends "base.html" %} 
{% load static %} 

{% block title %} Карта сайта - Медицинский центр ПроЗдоровье {% endblock %} 
{% block meta_title %} Карта сайта - Медицинский центр ПроЗдоровье {% endblock %} 
{% block description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %} 
{% block meta_description %} В мед. центре ПроЗдоровье вас ждут на прием профессиональные остеопаты, неврологи, эндокринологи и психотерапевты.🏥 Наши инструкторы по йоге и пилатесу приглашают записаться в группы или на индивидуальные занятия. ПроЗдоровье - здоровье начинается здесь! {% endblock %} 


{% block script %}
<script type=module src="{% static 'js/header.js' %}"></script>
<script type=module src="{% static 'js/footer.js' %}"></script>
{% endblock %}

{% block content %}
<div id=header></div>
<div class="container" style="margin-top: 60px; margin-bottom: 20px;">
    <div class="map-container">
        <h1 class="map__header">Карта сайта</h1>
            <ul>
                <li class="map__bullet-1">
                    <h5><a href="{% url 'services:speciality' speciality_slug='osteopatiya' %}">Услуги</a></h5>
                    <ul>
                        {% for speciality in specialities %}
                            <li class="map__bullet-2"><a href="
                            {% if speciality.is_displayed %}
                                {{ speciality.get_absolute_url }}
                            {% else %}
                                {{ specialities.0.get_absolute_url }}
                            {% endif %}">{{ speciality.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="map__bullet-1">
                    <h5><a href="{% url 'doctors:doctors' %}">Специалисты</a></h5>
                    <ul>
                        {% for doctor in doctors %}
                            <li class="map__bullet-2"><a href="{{ doctor.get_absolute_url }}">{{ doctor.last_name }} {{ doctor.first_name}} {{ doctor.patronymic }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="map__bullet-1">
                    <h5><a href="{% url 'prices:prices' %}">Цены</a></h5>
                </li>
                <li class="map__bullet-1">
                    <h5><a href="{% url 'landing:contacts' %}">О компании</a></h5>
                    <ul>
                        <li class="map__bullet-2"><a href="{% url 'landing:contacts' %}">Контакты</a></li>
                        <li class="map__bullet-2"><a href="{% url 'landing:juridical_info' %}">Юридическая информация</a></li>
                    </ul>
                </li>
            </ul>
        </div>
</div>
<div id=footer></div>
{% endblock %}